title: 신춘호 Profile
photo: /assets/img/profile.png
description: 재미있는 일을 찾는 18년차 개발자
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
resume: /docs/신춘호_이력서.pdf
profile:
  github: https://github.com/sch0718
  gitlab: https://gitlab.com/sch0718
  linkedin: https://www.linkedin.com/in/%EC%B6%98%ED%98%B8-%EC%8B%A0-451621185/
