title: 신춘호 Profile
description: 재미있는 일을 찾는 개발자
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
resume:
  pdf: https://buly.kr/4xXFBG0 # 원본 URL: https://drive.google.com/file/d/1uvEc5jLHOuzLUkWW73Q1PrhrGkpzg7Xu/view?usp=drive_link
  word: https://buly.kr/8TqOnbz # 원본 URL: https://docs.google.com/document/d/1TZGyigLgBU_D6fh7n5MIaZFwOAbSFtnn/edit?usp=drive_link&ouid=115324412023263415743&rtpof=true&sd=true
show_profile_link: true
show_portfolio: true
profile:
  github: https://github.com/sch0718
  gitlab: https://gitlab.com/sch0718
  linkedin: https://buly.kr/AapKIlY # 원본 URL: https://www.linkedin.com/in/%EC%B6%98%ED%98%B8-%EC%8B%A0-451621185/
show_projects_expand: true
expand_projects:
  yogiyo: true
  megazonecloud: true
  codepost: false
  ensystem_2016: false
  ydata: false
  ensystem_2015: false
  4csoft: false
  nextweb: false
  swotsoft: false
  topnwise: false
